org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

# Project Info
group=com.daqem.jobsplustoolsgenesiscompatibility
version=21.0.0
mod_id=jobsplustoolsgenesiscompatibility
mod_name=Jobs+ Tools Genesis Compatibility
mod_description=Adds compatibility between Jobs+ Tools and Genesis.
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/JobsPlusToolsGenesisCompatibility

# Publishing
supported_minecraft_versions=26.2
release_type=release
curse_forge_project_id=979423
curse_forge_dependencies=jobsplustools,genesis-official
modrinth_project_id=DVunHUgc
modrinth_dependencies=jobsplustools,genesis-official

# Dependencies
minecraft_version=26.2
neo_form_version=26.2-2
jobsplustools_version=21.1.0
genesis_version=1.6.3
genesis_framework_version=1.1.0
rei_version=26.2.820

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3